version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: lucopgen-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Password123456
      MYSQL_DATABASE: lucopgen_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  db_data:
